### ISSUE TITLE
Problem on NB 13 and Windows 11.

### ISSUE THREAD

**Issue by skostrze** [ranSprd/netbeans-pojomaker#2]
Every try to New from Json.. on Windows 11 returns Exception 

java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
..
at io.github.ranSprd.pojomaker.actions.NewFromJsonSourceFolderAction.extractPackageName(NewFromJsonSourceFolderAction.java:87)
...

Temporary I changed the code in extractPackageName method to:

String os = System.getProperty("os.name");
 if(os.startsWith("Windows 11")) return Optional.of( relativePath.replaceAll("/", "."));

then Plugin is working perfect.

**Comment by ranSprd** [comment]
I'm wondering because I assumed that the separator on windows systems is '\' and *not* '/'. Is there any special with your configuration? Are you using WSL1/2? 
Please don't get me wrong. I want to avoid other Windows 11 users having problems afterwards

**Comment by skostrze** [comment]
I checked the problem on the three different desktops with Windows 11. I have always the same error with regex. I'm not using any WSL but only one specific settings is a polish os language.

**Comment by ranSprd** [comment]
I hope the bug is solved with 0.4.3. The root cause was that ClassPath.getResourceName() returns always a string with "/" delimiters, nothing is depending on OS level there.

Thank you for reporting.
